name: Deltoid CI Build
on: [push]
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Deltoid
        run: |
          # Build with full optimizations and stealth flags
          gcc -shared -fPIC -O3 injected_lib.c -o libdeltoid.so -ldl -lpthread
          gcc -O3 Injector.c -o Deltoid_Launcher
          
      - name: Create Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Deltoid
          path: |
            libdeltoid.so
            Deltoid_Launcher
            init.lua
